name: "release version"

on:
  push:
    tags:
      - '1.*.*'


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ST_DOCKER_USER }}
          password: ${{ secrets.ST_DOCKER_PASSWORD }}
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/spot/web-service.googlepay:${{ steps.get_version.outputs.VERSION }}

  docker-deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - name: get uat docker yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/web-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=web-service.googlepay:.*$
        imagename=web-service.googlepay:${GITHUB_REF#refs/tags/}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m 'release web-service.googlepay:${GITHUB_REF#refs/tags/}' && git push; fi
